package main

import (
	"log"
	"os"
	"path"
	"path/filepath"
	"strings"

	"github.com/containers/podman/v6/pkg/systemd/parser"
)

func GetEnv(key, fallback string) string {
	value, exists := os.LookupEnv(key)
	if !exists {
		value = fallback
	}
	return value
}

func GetUnitGlobStr(userMode bool) string {
	baseDir := "/etc/"
	if userMode {
		baseDir = GetEnv("XDG_CONFIG_HOME", "~/.config/")
	}
	return baseDir + "npiperelay/systemd/*.pipe"
}

func GetUnitName(fileName string) string {
	base := filepath.Base(fileName)
	return base[:len(base)-len(filepath.Ext(base))]
}

func CreateSocketUnit(pipeUnit *parser.UnitFile) *parser.UnitFile {
	output := parser.NewUnitFile()
	output.AddComment("", "Automatically generated by npiperelay-generator")

	// Copy everything from Socket group
	for _, key := range pipeUnit.ListKeys("Socket") {
		val, exists := pipeUnit.Lookup("Socket", key)
		if !exists {
			panic("Key does not exist")
		}
		output.Add("Socket", key, val)
	}

	// Only "Accept=yes" is supported
	output.Set("Socket", "Accept", "yes")

	return output
}

func CreateServiceUnit(pipeUnit *parser.UnitFile, socketUnitName string) *parser.UnitFile {
	output := parser.NewUnitFile()
	output.AddComment("", "Automatically generated by npiperelay-generator")

	output.Set("Unit", "Requires", socketUnitName)
	output.Set("Service", "Type", "simple")
	output.Set("Service", "StandardInput", "socket")
	output.Set("Service", "StandardOutput", "socket")

	pipe, exists := pipeUnit.Lookup("NamedPipe", "Path")
	if !exists {
		panic("Path required")
	}

	execStart := "/usr/bin/npiperelay.exe"
	if pipeUnit.LookupBooleanWithDefault("NamedPipe", "AssuanSocket", false) {
		execStart += " -a"
	}
	if pipeUnit.LookupBooleanWithDefault("NamedPipe", "TerminateEOFSocket", false) {
		execStart += " -ei"
	}
	if pipeUnit.LookupBooleanWithDefault("NamedPipe", "TerminateEOFPipe", false) {
		execStart += " -ep"
	}
	if pipeUnit.LookupBooleanWithDefault("NamedPipe", "NotifyPipeAfterEOF", false) {
		execStart += " -s"
	}
	if pipeUnit.LookupBooleanWithDefault("NamedPipe", "Poll", false) {
		execStart += " -p"
	}
	if !pipeUnit.LookupBooleanWithDefault("NamedPipe", "PollIndefinitely", true) {
		execStart += " -l"
	}
	execStart += " " + pipe
	output.Set("Service", "ExecStart", execStart)

	return output
}

func WriteUnit(unit *parser.UnitFile) {
	file, err := os.OpenFile(unit.Path, os.O_WRONLY|os.O_CREATE, 0644)
	if err != nil {
		log.Fatal(err)
	}
	err = unit.Write(file)
	if err != nil {
		log.Fatal(err)
	}
	file.Close()
}

func main() {
	executable := path.Base(os.Args[0])
	outputDir := os.Args[1]

	userMode := strings.Contains(executable, "user-generators")
	matches, err := filepath.Glob(GetUnitGlobStr(userMode))
	if err != nil {
		log.Fatal(err)
	}

	for _, match := range matches {
		unitName := GetUnitName(match)
		unitFile, err := parser.ParseUnitFile(match)

		if err != nil {
			log.Fatal(err)
		}

		// Build systemd .socket unit file
		socketOut := CreateSocketUnit(unitFile)
		socketOut.Filename = unitName + ".socket"
		socketOut.Path = path.Join(outputDir, socketOut.Filename)

		// Build systemd .service unit file
		serviceOut := CreateServiceUnit(unitFile, socketOut.Filename)
		serviceOut.Filename = unitName + "@.service"
		serviceOut.Path = path.Join(outputDir, serviceOut.Filename)

		// Write files
		WriteUnit(socketOut)
		WriteUnit(serviceOut)

		// Handle install section
		wantedBy, exists := unitFile.Lookup("Install", "WantedBy")
		if exists {
			// Create symbolic link
			wantDir := path.Join(outputDir, wantedBy+".wants")
			os.Mkdir(wantDir, 0644)
			os.Symlink(socketOut.Path, path.Join(wantDir, socketOut.Filename))
		}

	}

	os.Exit(0)
}
